### ISSUE TITLE
流式音频生成报错[Errno -9996] Invalid output device (no default output device)

### ISSUE THREAD

**Issue by chenying99** [X-T-E-R/TTS-for-GPT-soVITS#15]
测试流式音频时，右上角弹出错误信息为：
[Errno -9996] Invalid output device (no default output device)

**Comment by chenying99** [comment]
我查找了一下资料，是pyaudio引发的异常
原因是我在linux的docker容器中运行，找不到音频设备

我目前的解决方法是将宿主机的音频设备映射到docker容器，添加参数--device /dev/snd

不知能不能，在服务器端不需要音频设备的情况下，实现流式音频输出？

**Comment by X-T-E-R** [comment]
对不起，这是一个bug，在修，你用api调用的话是正常的流式返回，但是gradio我还在研究

**Comment by chenying99** [comment]
大佬好，我用api流式调用时，也报错，报错信息如下：
`
| ERROR:    Exception in ASGI application
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 265, in __call__
  |     await wrap(partial(self.listen_for_disconnect, receive))
  |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 261, in wrap
  |     await func()
  |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
  |     message = await receive()
  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 535, in receive
  |     await self.message_event.wait()
  |   File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait
  |     await fut
  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f25929052b0
  | 
  | During handling of the above exception, another exception occurred:
  | 
  |   + Exception Group Traceback (most recent call last):
  |   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
  |   |     result = await app(  # type: ignore[func-returns-value]
  |   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |   |     return await self.app(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
  |   |     await super().__call__(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
  |   |     await self.middleware_stack(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |   |     raise exc
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |   |     await self.app(scope, receive, _send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |   |     await self.app(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |   |     raise exc
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |   |     await app(scope, receive, sender)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
  |   |     await self.middleware_stack(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
  |   |     await route.handle(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
  |   |     await self.app(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
  |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |   |     raise exc
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |   |     await app(scope, receive, sender)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 75, in app
  |   |     await response(scope, receive, send)
  |   |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 265, in __call__
  |   |     await wrap(partial(self.listen_for_disconnect, receive))
  |   |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |   |     raise BaseExceptionGroup(
  |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  |   +-+---------------- 1 ----------------
  |     | Traceback (most recent call last):
  |     |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 261, in wrap
  |     |     await func()
  |     |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 252, in stream_response
  |     |     chunk = chunk.encode(self.charset)
  |     | AttributeError: 'tuple' object has no attribute 'encode'
  |     +------------------------------------
`

**Comment by X-T-E-R** [comment]
> 这个问题解决了么？

修好了

**Comment by X-T-E-R** [comment]
请见 GSVI： https://github.com/X-T-E-R/GPT-SoVITS-Inference/commit/b99abc6d3c45e9e00b78032e38edafb2279a1bd5

**Comment by ahkimkoo** [comment]
> 请见 GSVI： [X-T-E-R/GPT-SoVITS-Inference@b99abc6](https://github.com/X-T-E-R/GPT-SoVITS-Inference/commit/b99abc6d3c45e9e00b78032e38edafb2279a1bd5)

刚提交的Inference/config.json的Json格式多了一个逗号，需要修正一下。

**Comment by X-T-E-R** [comment]
> > 请见 GSVI： [X-T-E-R/GPT-SoVITS-Inference@b99abc6](https://github.com/X-T-E-R/GPT-SoVITS-Inference/commit/b99abc6d3c45e9e00b78032e38edafb2279a1bd5)
> 
> 刚提交的Inference/config.json的Json格式多了一个逗号，需要修正一下。

对的，我删内容的时候忘了，谢谢提醒
