### ISSUE TITLE
多語言合成失敗 RuntimeError: shape '[1, 1, 1, 159]' is invalid for input of size 144

### ISSUE THREAD

**Issue by XUANNISSAN** [X-T-E-R/TTS-for-GPT-soVITS#19]
前端处理后的文本(每句): ['我是一个粉刷匠,O H！Y E S。 ']
ERROR:tts_backend:Exception on /tts [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\GPT-SoVITS\runtime\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\GPT-SoVITS\runtime\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\GPT-SoVITS\runtime\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\GPT-SoVITS\runtime\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Admin\GPT-SoVITS\runtime\lib\site-packages\flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "C:\Users\Admin\GPT-SoVITS\Inference\src\tts_backend.py", line 126, in tts
    sampling_rate, audio_data = next(gen)
  File "C:\Users\Admin\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 579, in run
    pred_semantic_list, idx_list = self.t2s_model.model.infer_panel(
  File "C:\Users\Admin\GPT-SoVITS\GPT_SoVITS\AR\models\t2s_model.py", line 553, in infer_panel
    xy_padding_mask.view(bsz, 1, 1, src_len).expand(-1, self.num_head, -1, -1)
RuntimeError: shape '[1, 1, 1, 159]' is invalid for input of size 144
INFO:werkzeug:127.0.0.1 - - [12/Mar/2024 16:40:35] "POST /tts HTTP/1.1" 500 -

**Comment by X-T-E-R** [comment]
OK，这是并行推理包的问题，将在新版本允许用户使用经典推理
