### ISSUE TITLE
infer_panel() got an unexpected keyword argument 'top_p'

### ISSUE THREAD

**Issue by mufeng520** [X-T-E-R/TTS-for-GPT-soVITS#2]
音频测试时提示
Traceback (most recent call last):
  File "D:\study\python\aimodel\GPT-SoVITS-beta\TTS-for-GPT-soVITS\tts_backend.py", line 9, in <module>
    from character_manage import load_character, character_name, get_wav_from_text_api
  File "D:\study\python\aimodel\GPT-SoVITS-beta\TTS-for-GPT-soVITS\character_manage.py", line 153, in <module>
    test_audio_save()
  File "D:\study\python\aimodel\GPT-SoVITS-beta\TTS-for-GPT-soVITS\character_manage.py", line 147, in test_audio_save
    fs, audio_to_save=get_wav_from_text_api("""这是一段音频测试""",'多语种混合')
  File "D:\study\python\aimodel\GPT-SoVITS-beta\TTS-for-GPT-soVITS\character_manage.py", line 143, in get_wav_from_text_api
    return get_tts_wav(ref_wav_path, prompt_text, prompt_language, text, text_language, top_k=top_k, top_p=top_p, temperature=temperature, ref_free=ref_free)
  File "D:\study\python\aimodel\GPT-SoVITS-beta\TTS-for-GPT-soVITS\inference_core.py", line 310, in get_tts_wav
    pred_semantic, idx = t2s_model.model.infer_panel(
TypeError: infer_panel() got an unexpected keyword argument 'top_p'

**Comment by X-T-E-R** [comment]
这是因为你的原项目版本低了，你需要更新花儿不哭的那个项目
