### ISSUE TITLE
源码不可用，缺少text依赖

### ISSUE THREAD

**Issue by msx15615634157** [X-T-E-R/TTS-for-GPT-soVITS#30]
from text import cleaned_text_to_sequence
from text.cleaner import clean_text

源码不可用啊，有说法么，上面两个依赖，不在pipy么

**Comment by Purewo** [comment]
我也遇到问题，(my-venv) D:\AI\TTS-for-GPT-soVITS-plug_in>python TTS_Webui.py
Traceback (most recent call last):
  File "D:\AI\TTS-for-GPT-soVITS-plug_in\TTS_Webui.py", line 19, in <module>
    from Inference.src.config_manager import Inference_Config
ModuleNotFoundError: No module named 'Inference'

**Comment by msx15615634157** [comment]
> 我也遇到问题，(my-venv) D:\AI\TTS-for-GPT-soVITS-plug_in>python TTS_Webui.py Traceback (most recent call last): File "D:\AI\TTS-for-GPT-soVITS-plug_in\TTS_Webui.py", line 19, in from Inference.src.config_manager import Inference_Config ModuleNotFoundError: No module named 'Inference'

这样可以改正：
from Inference.src.config_manager
换成
from src.config_manager

**Comment by Purewo** [comment]
谢谢指点！但是依旧存在错误，from tools.i18n.i18n import I18nAuto这个库的引入也有问题，我不知道之后还有多少问题，他貌似是一个基于GPT-SoVITS的插件，是不是有其他的启动方式

**Comment by L9qmzn** [comment]
> 谢谢指点！但是依旧存在错误，from tools.i18n.i18n import I18nAuto这个库的引入也有问题，我不知道之后还有多少问题，他貌似是一个基于GPT-SoVITS的插件，是不是有其他的启动方式

这类问题还挺多的。具体你的这个问题，可以在TTS_Webui.py的开头处理路径处像下面这样更改。然后from Inference.src.config_manager就不用更改了。
```
# now_dir = os.getcwd()
# sys.path.append(now_dir)
root_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root_path)
```

**Comment by Purewo** [comment]
> > 谢谢指点！但是依旧存在错误，from tools.i18n.i18n import I18nAuto这个库的引入也有问题，我不知道之后还有多少问题，他貌似是一个基于GPT-SoVITS的插件，是不是有其他的启动方式
> 
> 这类问题还挺多的。具体你的这个问题，可以在TTS_Webui.py的开头处理路径处像下面这样更改。然后from Inference.src.config_manager就不用更改了。
> 
> ```
> # now_dir = os.getcwd()
> # sys.path.append(now_dir)
> root_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
> sys.path.append(root_path)
> ```

现在已解决，下载了一个beta整合包，将src里面的py文件拖出来到项目根目录下解决问题，总感觉他这个整合包种类太多了，有点小混乱
